### ISSUE TITLE
TypeError: 'str' does not support the buffer interface Python 3.4.3 Windows 8.1 x64

### ISSUE THREAD

**Issue by bernardladenthin** [Varbin/xtea3#3]
Hi, I can't use the library.
Sorry for the first bug report. I was confused about the different library versions.
Python 3.4.3 says the following:

  File "xtea3.py", line 239, in encrypt
    tx = _encrypt(self.__key, fb, self.rounds/2, self.endian)
  File "xtea3.py", line 615, in _encrypt
    v0,v1 = struct.unpack(endian+"2L",block)
TypeError: 'str' does not support the buffer interface

Regards from Berlin, Bernard

**Comment by Varbin** [comment]
Sorry for this problem, and sorry that I haven't seen this bug before. Can you please send the full step to reproduce? 

It seems that you try to encrypt a string object (or having that as a key of IV), it must be bytes in python3.

This code should work:

```
import xtea3

toencrypt = b"something"*8
key = b"0123456789abcdef"
IV = b"random12"

o = xtea3.new(key=key, IV=IV)
assert o.decrypt(o.encrypt(toencrypt)) == toencrypt
```

Regards from Nordrhein-Westfalen, Simon
